spring:
  application:
    name: intranet
  datasource:
    url: jdbc:h2:mem:intranet   # BD en memoria: se recrea en cada arranque
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop     # Hibernate crea la tabla a partir de la entidad
  thymeleaf:
    cache: false

server:
  port: 8080
