-- Usuarios de la intranet
CREATE TABLE usuario (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  VARCHAR(100) NOT NULL UNIQUE,
    password  VARCHAR(100) NOT NULL,
    rol       VARCHAR(30)  NOT NULL,
    activo    BOOLEAN      NOT NULL DEFAULT TRUE
);

-- Preguntas frecuentes que responde el chatbot
CREATE TABLE faq (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pregunta       VARCHAR(500)  NOT NULL,
    respuesta      VARCHAR(4000) NOT NULL,
    palabras_clave VARCHAR(500),
    activa         BOOLEAN       NOT NULL DEFAULT TRUE
);

-- Registro de lo que se pregunta al chatbot
CREATE TABLE consulta_chat (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto      VARCHAR(1000) NOT NULL,
    respondida BOOLEAN       NOT NULL,
    fecha      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);